import type { Metadata } from "next";
import {
  Averia_Libre,
  Averia_Sans_Libre,
  Averia_Serif_Libre,
  DM_Sans,
} from "next/font/google";

import Footer from "@/components/home/Footer";
import NavBar from "@/components/home/NavBar";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const averia = Averia_Libre({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-averia",
});

const averiaSerif = Averia_Serif_Libre({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-averia-serif",
});

const averiaSans = Averia_Sans_Libre({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-averia-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${averiaSerif.variable} ${averia.variable} ${averiaSans.variable} font-body bg-tenton-bg text-tenton-black`}
      >
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
